In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import utils.data as data

train, test = data.get_train_test_split(0.01, 42)

In [3]:
dataset = data.Marconi100Dataset(test)
df, lab = dataset[0]

100%|██████████| 3/3 [00:04<00:00,  1.34s/it]


In [4]:
lab.unique()

array([0, 1])

In [5]:
df.shape

(13195, 460)

In [6]:
import torch

tensor = torch.ones(df.shape)
print(tensor.shape)

torch.Size([13195, 460])


In [10]:
import numpy as np

def generate_masks(M):
    masks = []
    for i in range(0, M):
        x = tensor.clone().detach()

        #get column indices for the features to mask
        col_idxs = np.random.choice(range(0, df.shape[1]), 10, replace=False)
        #get row indices for the samples to mask
        row_idxs = np.random.choice(range(0, df.shape[0]), 10, replace=False)
        if i == 0:
            print("col_idxs: ", col_idxs)
            print("row_idxs: ", row_idxs)
            for i in row_idxs:
                for j in col_idxs:
                    x[i][j] = 0

        mask = x > 0
        masks.append(mask)
    return masks

def generate_mask_V1(shape, n):
    
    # inefficiente
    n_mask = int(np.prod(shape) / n)
    
    mask = torch.ones(shape)
    print(np.count_nonzero(mask == 0), n_mask)
    
    while np.count_nonzero(mask == 0) < n_mask:
        
        # get column index for the element to mask
        col_idx = np.random.choice(range(shape[1]), replace=False)
        # get row index for the element to mask
        row_idx = np.random.choice(range(shape[0]), replace=False)
        mask[row_idx, col_idx] = 0
        
    return mask

def generate_mask_V2(shape, n):
    
    # molto più efficiente
    
    mask = torch.ones(np.prod(shape))
    
    n_mask = int(np.prod(shape) / n)
    
    # make sure as many as n_mask samples are masked
    mask[:n_mask] = 0
    
    mask = torch.reshape(mask, shape)
    
    # permute rows
    mask = np.random.permutation(mask)
    
    # permute columns
    mask = mask[:, np.random.permutation(mask.shape[1])]
    
    return mask

def generate_mask_V3(shape, n):
    
    # un po' più efficiente
    mask = np.ones(np.prod(shape))
    n_mask = int(np.prod(shape) / n)
    # make sure as many as n_mask samples are masked
    mask[:n_mask] = 0

    # permute elements
    mask = np.random.permutation(mask)

    # reshape to the input shape
    mask = torch.tensor(mask).reshape(shape)
    
    return mask

In [15]:
generate_mask_V3((5, 5), 2)

tensor([[1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 0.],
        [0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 1.]], dtype=torch.float64)

In [73]:
def generate_non_overlapping_masks(shape, n):
    masks = []
    prod = np.prod(shape)
    n_mask = int(prod / n)
    # set are much more efficient at removing
    not_used = set(i for i in range(prod))

    while len(masks) < n:
        mask = np.ones(prod)
        # choose from the aviable indices
        idxs = np.random.choice(tuple(not_used), n_mask, replace=False)
        # set to 0
        mask[idxs] = 0
        # mark as used
        not_used = not_used.difference(idxs)
        # reshape to the input shape
        mask = torch.tensor(mask).reshape(shape)
        masks.append(mask)
    
    masks = torch.stack(masks)
    assert ((masks.size(0) - masks.sum(0)) <= 1).all(), "Something wrong"
    return masks

In [76]:
%%timeit
s = set(range(100))
c = list(range(0, 100, 3))

for _ in range(100):
    a = s.difference(c)

218 µs ± 23.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [81]:
%%timeit
s = set(range(100))
c = list(range(0, 100, 3))

for _ in range(100):
    s2 = s.copy()
    for i in c:
        s2.remove(i)

526 µs ± 125 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [82]:
%%timeit
s = list(range(100))
c = list(range(0, 100, 3))

for _ in range(100):
    s2 = s.copy()
    for i in c:
        s2.remove(i)

2.3 ms ± 175 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [74]:
masks = generate_non_overlapping_masks((1024, 416), 20)

In [67]:
masks.size()

torch.Size([20, 1024, 416])

In [83]:
tensor.shape

torch.Size([13195, 460])

In [87]:
res = tensor.unfold(0, 1024, 512).permute(0, 2, 1)
print(res.shape)

torch.Size([24, 1024, 460])


In [111]:
masks = generate_mask_V1(tensor.shape, 2000)
# first_mask = masks[0]
# print indices of holes
# print(torch.logical_not(first_mask).nonzero())

CPU times: user 6 µs, sys: 1 µs, total: 7 µs
Wall time: 11.4 µs
0 3078


In [115]:
mask = generate_mask_V2(tensor.shape, 2000)
print(np.count_nonzero(mask == 0))
print(np.count_nonzero(mask == 0) + np.count_nonzero(mask) == np.prod(mask.shape))
# print indices of holes
# print(torch.logical_not(mask).nonzero())

CPU times: user 9 µs, sys: 0 ns, total: 9 µs
Wall time: 15.7 µs
tensor([1., 1., 1.,  ..., 1., 1., 1.])
tensor([0., 0., 0.,  ..., 1., 1., 1.])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])
3078
True
